version: "3.8"
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - "80:80"
    depends_on:
      - api
      - mongodb
      - redis
    networks:
      - mern-app
  api:
    build:
      dockerfile: Dockerfile
      context: ./server
    volumes:
      - "/app/node_modules"
      - "./server:/app"
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - redis
    networks:
      - mern-app
    restart: unless-stopped
  mongodb:
    image: "mongo:4.4.18"
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - mern-app
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local